/**
 * Extract 專屬活動 from Weebly events HTML into seed-events.sql
 */
const fs = require('fs');
const path = require('path');

const EVENTS_HTML = path.join(
  __dirname,
  '..',
  'htjwc.weebly.com',
  '2930532004242152347823560236602796321205.html'
);
const OUT_SQL = path.join(__dirname, '..', 'seed-events.sql');

function decodeEntities(html) {
  return html
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#8203;/g, '');
}

function stripTags(html) {
  return decodeEntities(
    html
      .replace(/<br\s*\/?>/gi, '\n')
      .replace(/<\/(p|div|tr|li)>/gi, '\n')
      .replace(/<[^>]+>/g, '')
  )
    .replace(/\r/g, '')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function sqlStr(s) {
  return "'" + String(s || '').replace(/'/g, "''") + "'";
}

function extractBlock(html, startMarker) {
  const start = html.indexOf(startMarker);
  if (start === -1) return '';
  const slice = html.slice(start);
  const end = slice.indexOf('</div><!-- end banner-wrap -->');
  return end === -1 ? slice : slice.slice(0, end);
}

function parseEvents(html) {
  const contentStart = html.indexOf('id="wsite-content"');
  if (contentStart === -1) return [];
  const contentHtml = html.slice(contentStart);

  const re = /<div><div class="wsite-multicol">[\s\S]*?<\/div><\/div><\/div>/g;
  const events = [];
  let match;
  let sort = 0;

  while ((match = re.exec(contentHtml)) !== null) {
    const block = match[0];
    const paraMatch = block.match(/<div class="paragraph">([\s\S]*?)<\/div>/);
    const imgMatch = block.match(/<img src="([^"]+)"/);
    const linkMatch = block.match(/<div class="wsite-image[\s\S]*?<a[^>]+href="([^"]+)"/);

    if (!paraMatch && !imgMatch) continue;

    let title = '';
    let body = '';
    if (paraMatch) {
      const paraHtml = paraMatch[1];
      const strongMatch = paraHtml.match(/<(?:strong|b)[^>]*>([\s\S]*?)<\/(?:strong|b)>/i);
      if (strongMatch) {
        title = stripTags(strongMatch[1]).replace(/\s+/g, ' ').trim();
        body = stripTags(paraHtml.replace(strongMatch[0], ''));
      } else {
        const full = stripTags(paraHtml);
        title = full.split(/\n|。/)[0].slice(0, 80).trim();
        body = full;
      }
    }

    if (!title && !body && !imgMatch) continue;
    if (!title) title = '專屬活動 ' + (sort + 1);

    events.push({
      title,
      body,
      image_url: imgMatch ? imgMatch[1] : '',
      link_url: linkMatch ? linkMatch[1] : '',
      sort_order: sort++,
      visible: 1,
    });
  }

  return events;
}

const html = fs.readFileSync(EVENTS_HTML, 'utf8');
const events = parseEvents(html);

const lines = [
  '-- Auto-generated by scripts/extract-events.js',
  'DELETE FROM events;',
  '',
];

for (const ev of events) {
  lines.push(
    'INSERT INTO events (title, body, image_url, link_url, sort_order, visible) VALUES (' +
      [
        sqlStr(ev.title),
        sqlStr(ev.body),
        sqlStr(ev.image_url),
        sqlStr(ev.link_url),
        ev.sort_order,
        ev.visible,
      ].join(', ') +
      ');'
  );
}

lines.push('');
fs.writeFileSync(OUT_SQL, lines.join('\n'), 'utf8');
console.log('Wrote', events.length, 'events to', OUT_SQL);
